### PR TITLE
Refactor project with `@11ty/eleventy` CMS

### PR DESCRIPTION
**Pull request by azerella**
If you're open to this @treese I'd like to trial a new, upcoming framework that's perfect for this kind of website project. 

By swapping over to it we can greatly simplify the number of custom scripts and local development logic that I've had to create. Less maintainability and using a popular CMS framework also makes things a bit more structured.

This PR should be a drop in replacement for `master`, the only difference is that the URLs need to change e.g `/about.html -> /about/index.html`

Let me know what you think, if we go ahead with this change I want to start tidying up the CSS and making the pages responsive / more accessible

### CODE REVIEW

**Comment by treese** [comment]
In principle I don't have any objection. Is there an easy way for me to preview what it would be like?

Also: I'm wondering that we'd probably like to keep a few key URLs working--I got a message the other day about a couple of .shtml file links that we didn't preserve in the previous conversion (they were not a big problem). Is there a way to add redirects to the new URLs?

Thanks.

**Comment by azerella** [comment]
@treese Awesome, the simplest way to preview this is to:

```
git clone git@github.com:aquamacs-emacs/aquamacs-web-site.git
git checkout feature/11ty-ssg
npm ci
npm run watch
```

Then navigate to http://localhost:8080

### Redirects

Admittedly, GitHub pages kinda sucks for redirects. The easiest thing for us to do is to create a mock file e.g `download.shtml` that just contains a `<meta http-equiv="refresh" content="1;url=http://aquamacs.org/download/index.html">`.

Alternatively, we'd have to move to another free static site host like [Netlify](https://www.netlify.com/)

**Comment by treese** [comment]
Is it possible to make the visible URLs be something some `https://aquamacs.org/about/` with the trailing slash to get the `index.html`, instead of including the `index.html` explicitly? I think other than that, I don't have any issues with switching it over; I'm hoping it enables us to rework the design and content easily.

**Comment by azerella** [comment]
@treese with GitHub pages, unfortunately URL rewrites aren't an option for now. We can achieve this by moving the hosting to the free platform Netlify as mentioned above but totally understand if you think the move outweighs the effort then we'll probably have to close this PR

**Comment by treese** [comment]
To clarify, is the issue that we can’t also rewrite URLs, or that they always have the unusual format and there’s no way to change that?

**Comment by treese** [comment]
Should have closed this a while ago, since it's obsolete.

**Pull request closed without merging**
