### PR TITLE
a few typos

### PR DESCRIPTION
**Pull request by brandelune**

### CODE REVIEW

**Comment by adamzerella** [comment]
@brandelune Good find! I wonder how long these typos have been sitting around :)

Before we merge this, can you please run the build script with `npm run build` to generate the HTML output? Speaking to @treese I think we'll add in a pre-commit hook in or update the pipeline so this doesn't happen in the future.

**Review by azerella — CHANGES_REQUESTED** [review]
@brandelune Good find! I wonder how long these typos have been sitting around :)

Before we merge this, can you please run the build script with npm run build to generate the HTML output? Speaking to @treese I think we'll add in a pre-commit hook in or update the pipeline so this doesn't happen in the future.

**Comment by brandelune** [comment]
I did what you say and git only gives me modifications to package-lock.json, which does not seem relevant to the site... What am I supposed to do with that ?

**Review by azerella — APPROVED** [review]

**Comment by azerella** [comment]
> I did what you say and git only gives me modifications to package-lock.json, which does not seem relevant to the site... What am I supposed to do with that ?

That's ok! I think in the interim we'll just merge this and #17 and sort it out later :)

**Pull request merged**
